# version: "3"

services:
  app:
    container_name: tefiti-svc
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    # env_file:
    #   - .env
    # volumes:
    #   - ".:/app"
    ports:
      - 7044:3003
